# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://HenryKenlay.github.io/graphtools/"

git_url = "https://github.com/HenryKenlay/graphtools/tree/master/"

def custom_doc_links(name): return None