# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"non_pendant_edges": "00_graphtools.ipynb",
         "is_pendant": "00_graphtools.ipynb",
         "has_isolated_nodes": "00_graphtools.ipynb",
         "sample_nodes": "01_sampling.ipynb",
         "sample_node": "01_sampling.ipynb",
         "laplacian": "02_spectral.ipynb",
         "laplacian_distance": "02_spectral.ipynb",
         "sparse_2norm": "02_spectral.ipynb"}

modules = ["graphtools.py",
           "sampling.py",
           "spectral.py"]

doc_url = "https://HenryKenlay.github.io/grapht/"

git_url = "https://github.com/HenryKenlay/grapht/tree/master/"

def custom_doc_links(name): return None
