# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"non_pendant_edges": "00_graphtools.ipynb",
         "is_pendant": "00_graphtools.ipynb",
         "has_isolated_nodes": "00_graphtools.ipynb",
         "edges_removed": "00_graphtools.ipynb",
         "laplacian": "00_graphtools.ipynb",
         "sample_nodes": "01_sampling.ipynb",
         "sample_node": "01_sampling.ipynb",
         "khop_neighbourhood": "01_sampling.ipynb",
         "dilate": "01_sampling.ipynb",
         "sample_edges": "01_sampling.ipynb",
         "khop_subgraph": "01_sampling.ipynb",
         "sparse_norm": "02_metrics.ipynb",
         "sparse_2norm": "02_metrics.ipynb",
         "sparse_maxnorm": "02_metrics.ipynb",
         "laplacian_distance": "02_metrics.ipynb",
         "LineDistances": "02_metrics.ipynb",
         "average_gmdegree": "02_metrics.ipynb",
         "edge_degree_gm": "02_metrics.ipynb",
         "khop_edge_deletion": "03_perturb.ipynb",
         "highlight_edges": "04_plotting.ipynb",
         "highlight_edges_grapht": "04_plotting.ipynb",
         "heatmap": "04_plotting.ipynb",
         "sfdp_layout": "04_plotting.ipynb",
         "neato_layout": "04_plotting.ipynb",
         "fdp_layout": "04_plotting.ipynb",
         "get_graph_tool_graph": "04_plotting.ipynb",
         "get_networkx_graph": "04_plotting.ipynb",
         "nxpos_to_graphtpos": "04_plotting.ipynb",
         "cora": "05_data.ipynb",
         "pubmed": "05_data.ipynb",
         "citeseer": "05_data.ipynb",
         "amazon_photo": "05_data.ipynb",
         "amazon_computers": "05_data.ipynb",
         "microsoft_physics": "05_data.ipynb",
         "microsoft_cs": "05_data.ipynb",
         "make_planar_graph": "05_data.ipynb",
         "BAGraph": "05_data.ipynb",
         "SensorGraph": "05_data.ipynb",
         "CoraGraph": "05_data.ipynb"}

modules = ["graphtools.py",
           "sampling.py",
           "metrics.py",
           "perturb.py",
           "plotting.py",
           "data.py"]

doc_url = "https://HenryKenlay.github.io/grapht/"

git_url = "https://github.com/HenryKenlay/grapht/tree/master/"

def custom_doc_links(name): return None
