# AUTOGENERATED! DO NOT EDIT! File to edit: 04_plotting.ipynb (unless otherwise specified).

__all__ = ['highlight_edges']

# Cell
import matplotlib.pyplot as plt
import networkx as nx

# Cell
def highlight_edges(G, edges, ax, pos):
    "Draws the graph G with edges in `edges` drawn in red"
    nx.draw_networkx_nodes(G, pos=pos, node_size=10, ax=ax)
    nx.draw_networkx_edges(G, pos=pos, edgelist=set(G.edges()) - set(edges), ax=ax)
    nx.draw_networkx_edges(G, pos=pos, edgelist=edges, ax=ax, edge_color='red')
    return ax