name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
          miniconda-version: 'latest'
    - name: Install graphtool
      run: |
        echo 'deb http://downloads.skewed.de/apt/bionic bionic universe' | sudo tee -a /etc/apt/sources.list
        echo 'deb-src http://downloads.skewed.de/apt/bionic bionic universe' | sudo tee -a /etc/apt/sources.list
        sudo apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
        sudo apt-get update
        sudo apt-get install python3-graph-tool
        git clone https://git.skewed.de/count0/graph-tool.git
        cd graph-tool
        ./configure
        make
        make install
        cd ../
        python -c "from graph_tool.all import *"
    - name: Install the library
      run: |
        pip install nbdev jupyter
        pip install -e .
    - name: Read all notebooks
      run: |
        nbdev_read_nbs
    - name: Check if all notebooks are cleaned
      run: |
        echo "Check we are starting with clean git checkout"
        if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
        echo "Trying to strip out notebooks"
        nbdev_clean_nbs
        echo "Check that strip out was unnecessary"
        git status -s # display the status to see which nbs need cleaning up
        if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_git_hooks"; false; fi
    - name: Check if there is no diff library/notebooks
      run: |
        if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi
    - name: Run tests
      run: |
        nbdev_test_nbs
